image: 
  repository: pomceph/netflix
  tag: 244d8ae
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount: 
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false