image: 
  repository: pomceph/netflix
  tag: f42a74b
  pullPolicy: IfNotPreset
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
servcieAccount: 
  enabled: false
autoscaling:
  enabled: false